version: '3.8'
services:
  moogla:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "11434:11434"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MOOGLA_MODEL=codellama:13b
    volumes:
      - ./models:/models
    restart: always
