site_name: Moogla Documentation
site_url: https://rehkad.github.io/Moogla
docs_dir: docs
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Setup: setup.md
  - Plugin Development: plugins.md
  - Authentication: authentication.md
  - Web UI: web_ui.md
